# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  phpunit:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
      - run: echo "PHP Unit Tests"
      #- run: phpunit --bootstrap tests/TestBootstrap.php tests
  csslint:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: sudo npm install -g grunt-cli
      - run: sudo npm install grunt
      - run: sudo npm install grunt-contrib-csslint
      - run: grunt csslint
workflows:
  version: 2
  build:
    jobs:
      - phpunit
      - csslint
